'use client';

import { useAuth } from "@clerk/nextjs";
import { useRouter, useParams } from "next/navigation";
import { useState, useEffect } from "react";
import { renderMarkdown, setupMarkdownRenderer } from '@/lib/markdown';
import { NoteShareManager } from '@/app/components/ShareControls';

interface Note {
  _id: string;
  title: string;
  description: string;
  content: string;
  createdAt: string;
  status: string;
  originalFileName?: string;
  flashcards: Flashcard[];
  quizQuestions: QuizQuestion[];
  class: string;
  error?: string;
}

interface UserClass {
  _id: string;
  name: string;
  description: string;
}

interface Flashcard {
  front: string;
  back: string;
}

interface QuizQuestion {
  question: string;
  wrongAnswers: string[];
  correctAnswer: string;
  explanation: string;
  hint?: string;
}

export default function NotePage({
  params
}: {
  params: Promise<{ id: string }>
}) {
  const { isLoaded, isSignedIn } = useAuth();
  const router = useRouter();
  const { id } = useParams();
  const [note, setNote] = useState<Note | null>(null);
  const [loading, setLoading] = useState(true);
  const [noteClass, setNoteClass] = useState<string>('');
  const [availableClasses, setAvailableClasses] = useState<UserClass[]>([]);
  const [showTranscript, setShowTranscript] = useState(false);
  const [transcript, setTranscript] = useState<string | null>(null);
  const [transcriptLoading, setTranscriptLoading] = useState(false);
  const [transcriptAutoGenerated, setTranscriptAutoGenerated] = useState(false);
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [retrying, setRetrying] = useState(false);
  const [editingNote, setEditingNote] = useState(false);
  const [noteDraft, setNoteDraft] = useState({ title: '', content: '' });
  const [editingTranscript, setEditingTranscript] = useState(false);
  const [transcriptDraft, setTranscriptDraft] = useState('');
  const [savingEdit, setSavingEdit] = useState(false);
  const [editError, setEditError] = useState('');

  const startNoteEdit = () => {
    if (!note) return;
    setNoteDraft({ title: note.title, content: note.content });
    setEditError('');
    setEditingNote(true);
  };

  const saveNoteEdit = async () => {
    if (!note || savingEdit) return;
    const title = noteDraft.title.trim();
    if (!title) { setEditError('Title can’t be empty.'); return; }
    setSavingEdit(true);
    setEditError('');
    try {
      const response = await fetch(`/api/notes/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, content: noteDraft.content }),
      });
      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || 'Could not save changes');
      }
      setNote({ ...note, title, content: noteDraft.content });
      setEditingNote(false);
    } catch (error) {
      setEditError(error instanceof Error ? error.message : 'Could not save changes');
    } finally {
      setSavingEdit(false);
    }
  };

  const startTranscriptEdit = () => {
    setTranscriptDraft(transcript || '');
    setEditError('');
    setEditingTranscript(true);
  };

  const saveTranscriptEdit = async () => {
    if (savingEdit) return;
    setSavingEdit(true);
    setEditError('');
    try {
      const response = await fetch(`/api/notes/${id}/transcript`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ transcript: transcriptDraft }),
      });
      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(data.error || 'Could not save transcript');
      }
      setTranscript(transcriptDraft);
      setTranscriptAutoGenerated(false);
      setEditingTranscript(false);
    } catch (error) {
      setEditError(error instanceof Error ? error.message : 'Could not save transcript');
    } finally {
      setSavingEdit(false);
    }
  };

  const handlePageRetry = async () => {
    setRetrying(true);
    try {
      const response = await fetch(`/api/notes/${id}/retry`, {
        method: 'POST',
      });
      if (response.ok) {
        fetchNote();
      } else {
        const errData = await response.json();
        alert(errData.error || 'Failed to retry');
      }
    } catch (error) {
      console.error('Failed to retry note:', error);
      alert('Failed to retry note. Please try again.');
    } finally {
      setRetrying(false);
    }
  };

  useEffect(() => {
    if (note && (note.status === 'processing' || note.status === 'queued')) {
      const interval = setInterval(() => {
        fetchNote();
      }, 3000);
      return () => clearInterval(interval);
    }
  }, [note?.status]);

  useEffect(() => {
    setupMarkdownRenderer();

    const initPage = async () => {
      if (isLoaded && !isSignedIn) {
        router.push('/');
        return;
      }

      if (isLoaded && isSignedIn) {
        fetchNote();
      }
    };

    initPage();
  }, [isLoaded, isSignedIn]);

  useEffect(() => {
    const fetchClasses = async () => {
      try {
        const response = await fetch('/api/user/classes');
        if (response.ok) {
          const data = await response.json();
          setAvailableClasses(data);
        } else {
          console.error('Failed to fetch available classes:', response.statusText);
        }
      } catch (error) {
        console.error('Failed to fetch available classes:', error);
      }
    };

    if (isLoaded && isSignedIn) {
      fetchClasses();
    }
  }, [isLoaded, isSignedIn]);

  const fetchNote = async () => {
    try {
      const response = await fetch(`/api/notes/${id}`);
      if (response.ok) {
        const data = await response.json();
        setNote(data);
        setFlashcards(data.flashcards || []);
        setNoteClass(data.class || '');
        setQuizQuestions(data.quizQuestions || []);

      } else if (response.status === 404) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to fetch note:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteNote = async () => {
    if (!confirm('Are you sure you want to delete this note?')) {
      return;
    }

    try {
      const response = await fetch(`/api/notes/${id}`, {
        method: 'DELETE',
      });
      if (response.ok) {
        router.push('/');
      }
    } catch (error) {
      console.error('Failed to delete note:', error);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const fetchTranscript = async () => {
    if (transcript !== null) return;
    
    setTranscriptLoading(true);
    try {
      const response = await fetch(`/api/notes/${id}/transcript`);
      if (response.ok) {
        const text = await response.text();
        setTranscript(text);
        if (note && text === note.content) {
          setTranscriptAutoGenerated(true);
        }
      } else {
        setTranscript('');
      }
    } catch (error) {
      console.error('Failed to fetch transcript:', error);
      setTranscript('');
    } finally {
      setTranscriptLoading(false);
    }
  };

  const toggleTranscript = () => {
    if (!showTranscript && transcript === null) {
      fetchTranscript();
    }
    setShowTranscript(!showTranscript);
  };

  const downloadMarkdown = () => {
    if (!note) return;
    
    const blob = new Blob([note.content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyMarkdown = async () => {
    if (!note) return;
    
    try {
      await navigator.clipboard.writeText(note.content);
      alert('Markdown copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy markdown:', error);
      alert('Failed to copy to clipboard');
    }
  };

  const downloadTranscript = () => {
    if (!transcript) return;
    
    const blob = new Blob([transcript], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${note?.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const copyTranscript = async () => {
    if (!transcript) return;
    
    try {
      await navigator.clipboard.writeText(transcript);
      alert('Transcript copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy transcript:', error);
      alert('Failed to copy to clipboard');
    }
  };

  const saveNoteClass = async (newClassValue: string) => {
    if (!note || newClassValue === note.class) return;

    try {
      const response = await fetch(`/api/notes/${id}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ class: newClassValue }),
      });

      if (response.ok) {
        setNote(prevNote => prevNote ? { ...prevNote, class: noteClass } : null);
        alert('Note class updated successfully!');
      } else {
        alert('Failed to update note class.');
      }
    } catch (error) {
      console.error('Failed to update note class:', error);
      alert('Failed to update note class.');
    }
  };

  if (!isLoaded || loading) {
    return (
      <div className="container">
        <div className="card">
          <p>Loading...</p>
        </div>
      </div>
    );
  }

  if (!isSignedIn) {
    return null;
  }

  if (!note) {
    return (
      <div className="container">
        <div className="card">
          <p>Note not found.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <button onClick={() => router.back()} className="btn btn-secondary">
          <span aria-hidden="true">← </span>Back
        </button>
        <button onClick={deleteNote} className="btn btn-danger">
          Delete Note
        </button>
        <div style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button onClick={downloadMarkdown} className="btn btn-primary">
            <span aria-hidden="true">↓ </span>Download MD
          </button>
          <button onClick={copyMarkdown} className="btn btn-secondary">
            <span aria-hidden="true">📋 </span>Copy MD
          </button>
          <button 
            onClick={toggleTranscript} 
            className={`btn ${showTranscript ? 'btn-primary' : 'btn-secondary'}`}
          >
            <span aria-hidden="true">{showTranscript ? '✕ ' : '👁 '}</span>{showTranscript ? 'Hide Transcript' : 'Show Transcript'}
          </button>
          {transcript !== null && (
            <>
              <button onClick={downloadTranscript} className="btn btn-primary">
                ↓ Save TXT
              </button>
              <button onClick={copyTranscript} className="btn btn-secondary">
                <span aria-hidden="true">📋 </span>Copy TXT
              </button>
            </>
          )}
          {flashcards.length > 0 && (
            <button 
              onClick={() => router.push(`/note/${id}/flashcards`)}
              className="btn btn-secondary"
            >
              <span aria-hidden="true">🎴 </span>Flashcards ({flashcards.length})
            </button>
          )}
          {quizQuestions.length > 0 && (
            <button 
              onClick={() => router.push(`/note/${id}/quiz`)}
              className="btn btn-secondary"
            >
              <span aria-hidden="true">📝 </span>Quiz ({quizQuestions.length})
            </button>
          )}
          <button 
            onClick={() => router.push(`/note/${id}/chat`)}
            className="btn btn-secondary"
          >
            <span aria-hidden="true">💬 </span>Chat
          </button>
          <NoteShareManager noteId={String(id)} canShare={note.status === 'completed'} />
        </div>
      </div>

      
      <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <label htmlFor="note-class-select" style={{ fontWeight: 'bold', whiteSpace: 'nowrap' }}>Note Class:</label>
        <select
          id="note-class-select"
          value={noteClass}
          onChange={async (e) => {
            setNoteClass(e.target.value);
            await saveNoteClass(e.target.value);
          }}
          style={{
            padding: '8px 12px',
            border: '1px solid #e2e8f0',
            borderRadius: '6px',
            flexGrow: 1,
            maxWidth: '300px',
            backgroundColor: 'white',
          }}
        >
          <option value="">None</option>
          {availableClasses.map((cls) => (
            <option key={cls._id} value={cls.name}>
              {cls.name}
            </option>
          ))}
        </select>
      </div>

      <div className="card">
        <header style={{ marginBottom: '30px', borderBottom: '1px solid #e2e8f0', paddingBottom: '20px' }}>
          <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '10px' }}>
            {note.title}
          </h1>
          <p style={{ color: '#6b7280', fontSize: '16px', marginBottom: '10px' }}>
            {note.description}
          </p>
          <p style={{ color: '#9ca3af', fontSize: '14px' }}>
            Created on {formatDate(note.createdAt)}
          </p>
        </header>

        {note.status === 'processing' || note.status === 'queued' ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>
            <p>This note is still being processed. Please check back in a few minutes.</p>
          </div>
        ) : note.status === 'error' ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>
            <p style={{ color: '#ef4444', fontWeight: 'bold', fontSize: '18px', marginBottom: '15px' }}>
              <span aria-hidden="true">⚠️ </span>Processing Failed
            </p>
            <p style={{ color: '#6b7280', marginBottom: '20px' }}>
              {note.error || 'An error occurred during audio processing.'}
            </p>
            <button onClick={handlePageRetry} className="btn btn-primary" disabled={retrying}>
              {retrying ? 'Retrying...' : 'Retry Processing'}
            </button>
          </div>
        ) : editingNote ? (
          <div className="edit-panel">
            <label htmlFor="note-edit-title" className="form-label">Title</label>
            <input
              id="note-edit-title"
              className="form-input"
              value={noteDraft.title}
              onChange={(e) => setNoteDraft({ ...noteDraft, title: e.target.value })}
            />
            <label htmlFor="note-edit-content" className="form-label">Note (Markdown)</label>
            <textarea
              id="note-edit-content"
              className="form-input edit-textarea"
              value={noteDraft.content}
              onChange={(e) => setNoteDraft({ ...noteDraft, content: e.target.value })}
            />
            {editError && <p className="share-error" role="alert">{editError}</p>}
            <div className="share-actions">
              <button type="button" className="btn btn-primary" onClick={saveNoteEdit} disabled={savingEdit}>
                {savingEdit ? 'Saving…' : 'Save changes'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => setEditingNote(false)} disabled={savingEdit}>
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <>
            {note.status === 'completed' && (
              <div className="edit-toolbar">
                <button type="button" className="btn btn-secondary" onClick={startNoteEdit}>
                  <span aria-hidden="true">✎ </span>Edit note
                </button>
              </div>
            )}
            <div
              className={`markdown-content ${noteClass}`}
              dangerouslySetInnerHTML={{ __html: renderMarkdown(note.content) }}
            />
          </>
        )}

        {showTranscript && (
          <div style={{ marginTop: '30px', borderTop: '1px solid #e2e8f0', paddingTop: '20px' }}>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold', marginBottom: '15px' }}>
              Original Transcript
            </h2>
            {transcriptLoading ? (
              <p>Loading transcript...</p>
            ) : transcript ? (
              <>
                {transcriptAutoGenerated && (
                  <div style={{ 
                    marginBottom: '15px', 
                    padding: '12px', 
                    backgroundColor: '#fef3c7', 
                    border: '1px solid #f59e0b',
                    borderRadius: '6px',
                    fontSize: '14px',
                    color: '#92400e'
                  }}>
                    <span aria-hidden="true">ℹ️ </span>This note was created before transcript storage was added. The transcript has been auto-generated from the note content.
                  </div>
                )}
{editingTranscript ? (
                  <div className="edit-panel">
                    <label htmlFor="transcript-edit" className="form-label">Correct the transcript</label>
                    <textarea
                      id="transcript-edit"
                      className="form-input edit-textarea"
                      value={transcriptDraft}
                      onChange={(e) => setTranscriptDraft(e.target.value)}
                    />
                    {editError && <p className="share-error" role="alert">{editError}</p>}
                    <div className="share-actions">
                      <button type="button" className="btn btn-primary" onClick={saveTranscriptEdit} disabled={savingEdit}>
                        {savingEdit ? 'Saving…' : 'Save transcript'}
                      </button>
                      <button type="button" className="btn btn-secondary" onClick={() => setEditingTranscript(false)} disabled={savingEdit}>
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className="edit-toolbar">
                      <button type="button" className="btn btn-secondary" onClick={startTranscriptEdit}>
                        <span aria-hidden="true">✎ </span>Correct transcript
                      </button>
                    </div>
                <div 
                      className="card"
                      style={{ 
                        backgroundColor: '#f8fafc', 
                        padding: '20px',
                        whiteSpace: 'pre-wrap',
                        fontFamily: 'ui-monospace, SFMono-Regular, monospace',
                        fontSize: '14px',
                        lineHeight: '1.6',
                        maxHeight: '500px',
                        overflowY: 'auto'
                      }}
                    >
                      {transcript}
                    </div>
                  </>
                )}
              </>
            ) : (
              <p>No transcript available for this note.</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
